#!/bin/bash
mv ARCHITECTURE_DIAGRAMS.md docs/architecture/
mv SYSTEM_ARCHITECTURE.md docs/architecture/
mv SYSTEM_WIRING_DIAGRAM.md docs/architecture/
mv INTEGRATION_VISUAL_MAP.md docs/architecture/
mv API_QUICK_REFERENCE.md docs/architecture/

mv DELIVERABLES_CHECKLIST.md docs/checklists/
mv DELIVERABLES_MLS.md docs/checklists/
mv DEPLOYMENT_SETUP_COMPLETE.md docs/checklists/
mv DEPLOYMENT_SUMMARY.md docs/checklists/
mv FINAL_CHECKLIST.md docs/checklists/
mv FILE_MANAGEMENT_DEPLOYMENT_CHECKLIST.md docs/checklists/
mv IMPLEMENTATION_COMPLETE.md docs/checklists/
mv IMPLEMENTATION_COMPLETE_V2.md docs/checklists/
mv FILE_MANIFEST.md docs/checklists/
mv FILE_INVENTORY.md docs/checklists/
mv FILES_CREATED_THIS_SESSION.txt docs/checklists/
mv PHASE_3_EXECUTIVE_SUMMARY.md docs/checklists/
mv PROJECT_DELIVERY_SUMMARY.md docs/checklists/
mv SESSION_COMPLETION_SUMMARY.md docs/checklists/
mv SESSION_DEPLOYMENT_COMPLETE.md docs/checklists/
mv COMPLETE_PROJECT_SUMMARY.md docs/checklists/
mv FINAL_PROJECT_SUMMARY.md docs/checklists/

mv 20-TILE-QUICK-REFERENCE.md docs/implementation/
mv 20-TILE_DASHBOARD_IMPLEMENTATION.md docs/implementation/
mv ADVANCED_FEATURES_GUIDE.md docs/implementation/
mv AI_AGENT_MLS_INTEGRATION_GUIDE.md docs/implementation/
mv AUTONOMOUS_AGENT_QUICK_REFERENCE.md docs/implementation/
mv AUTONOMOUS_AGENT_SESSION_COMPLETION.md docs/implementation/
mv AUTONOMOUS_AGENT_SYSTEM.md docs/implementation/
mv CRM_QUICK_TEMPLATES_COMPLIANCE_GUIDE.md docs/implementation/
mv CRM_QUICK_TEMPLATES_IMPLEMENTATION_SUMMARY.md docs/implementation/
mv FEATURE_TILES_IMPLEMENTATION.md docs/implementation/
mv FILE_MANAGEMENT_GUIDE.md docs/implementation/
mv FILE_MANAGEMENT_INTEGRATION.md docs/implementation/
mv FILE_MANAGEMENT_QUICK_REFERENCE.md docs/implementation/
mv FILE_MANAGEMENT_README.md docs/implementation/
mv FILE_MANAGEMENT_SUMMARY.md docs/implementation/
mv FULL_INTEGRATION_GUIDE.md docs/implementation/
mv IMPLEMENTATION_GUIDE.md docs/implementation/
mv IMPLEMENTATION_SUMMARY.md docs/implementation/
mv IMPLEMENTATION_STATUS_REPORT.md docs/implementation/
mv INTEGRATION_COMPARISON.md docs/implementation/
mv INTEGRATION_ROADMAP.md docs/implementation/
mv INTEGRATION_SUMMARY.md docs/implementation/
mv KUBERNETES_DEPLOYMENT_GUIDE.md docs/implementation/
mv MLS_INTEGRATION_GUIDE.md docs/implementation/
mv MLS_QUICK_START.md docs/implementation/
mv MULTI_COMPANY_IMPLEMENTATION_ROADMAP.md docs/implementation/
mv PHASE_4_MLS_IMPLEMENTATION.md docs/implementation/
mv QUICKSTART_FEATURES.md docs/implementation/
mv QUICKSTART_WINDOWS.md docs/implementation/
mv QUICK_ACTIONS_IMPLEMENTATION.md docs/implementation/
mv QUICK_REFERENCE.md docs/implementation/
mv QUICK_START_INTEGRATION.md docs/implementation/
mv QUICK_START_REFERENCE.md docs/implementation/
mv README_DOCUMENTATION.md docs/implementation/
mv README_MLS.md docs/implementation/
mv SECURITY.md docs/implementation/
mv UBUNTU_DEPLOYMENT_GUIDE.md docs/implementation/
mv MASTER_PROGRAMMING_GUIDE.md docs/implementation/

mv DOCUMENTATION_INDEX.md docs/
mv FILE_INDEX.md docs/
mv FILE_MANAGEMENT_DOCUMENTATION_INDEX.md docs/
mv MLS_DOCUMENTATION_INDEX.md docs/
